 log_file: /var/log/tests/changes_demo.log
 log_level: DEBUG
 remote_user: root

 nodes:
    vm9:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    vm10:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    vm11:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    vm12:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]

 peers:

 clients:
    vm12:

 distribute:
     dist_count: 4
     transport: tcp

 replicate:
     replica: 3
     transport: tcp

 dist_rep:
     dist_count: 2
     replica: 2
     transport: tcp

 disperse:
     disperse: 4
     redundancy: 2
     transport: tcp

 dist_disperse:
     dist_count: 2
     disperse: 4
     redundancy: 2
     transport: tcp

 global_mode: False

 volumes:
    hosdu:
        voltype: replicate
        nodes: [ vm9, vm10, vm11 ]
        peers:
        clients: [ vm12 ]
        mount_proto: glusterfs
        mountpoint: '/mnt/glusterfs'
