 log_file: /var/log/tests/distaf_test_run.log
 log_level: DEBUG
 remote_user: root

 servers:
    server-vm1:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    server-vm2:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    server-vm3:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    server-vm4:
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]

 clients:
     client-vm:
