 log_file: /var/log/tests/config_changes.log
 log_level: DEBUG
 remote_user: root

 servers:
    spitfire:
        devices: ["/dev/vdb", "/dev/vdc"]
    mustang:
        devices: ["/dev/vdb", "/dev/vdc"]
    typhoon:
        devices: ["/dev/vdb", "/dev/vdc"]
    harrier:
        devices: ["/dev/vdb", "/dev/vdc"]
    falcon:
        devices: ["/dev/vdb", "/dev/vdc"]
    hornet:
        devices: ["/dev/vdb", "/dev/vdc"]
    interceptor:
        devices: ["/dev/vdb", "/dev/vdc"]
    lightning:
        devices: ["/dev/vdb", "/dev/vdc"]

 clients:
    interceptor:
    lightning:

 distribute:
     dist_count: 4
     trans_type: tcp

 replicate:
     replica: 3
     trans_type: tcp

 dist_rep:
     dist_count: 2
     replica: 2
     trans_type: tcp

 disperse:
     disperse: 8
     redundancy: 2
     trans_type: tcp

 dist_disperse:
     dist_count: 2
     disperse: 8
     redundancy: 2
     trans_type: tcp

 global_mode: True

 volumes:
    hosdu:
        voltype: dist_rep
        servers: [ spitfire, mustang, typhoon, harrier ]
        peers:
        clients: [ interceptor ]
        mount_proto: glusterfs
        mountpoint: '/mnt/glusterfs'
    testvol:
        voltype: disperse
        servers: [ falcon, hornet, interceptor, lightning ]
        peers:

 geo-rep:
    master:
    slave:
