 log_file: /var/log/tests/distaf_test_run.log
 log_level: DEBUG
 remote_user: root
 servers:
    -   host: server-vm1
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    -   host: server-vm2
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    -   host: server-vm3
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
    -   host: server-vm4
        devices: ["/dev/vdb", "/dev/vdc", "/dev/vdd", "/dev/vde"]
 clients:
    -   host: client-vm1
    -   host: client-vm2
